services:
  identityprovider:
    image: nono/idp:latest
    build:
      context: .
      dockerfile: Idp.Api/Dockerfile
    ports:    
      - "5082:80"
      - "7254:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
    volumes:
      - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    depends_on:
      - database
  
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Guilherme123@
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data: